[package]
name = "solana-stake-program"
version = "1.0.0"
description = "Solana BPF Stake Program"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/stake-program"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
bincode = "1.3.3"
borsh = { version = "1.5.1", features = ["derive", "unstable__schema"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-program = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
thiserror = "1.0.63"

[dev-dependencies]
solana-program-test = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
solana-sdk = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
solana-vote-program = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
test-case = "3.3.1"

[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
solana-sdk = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
solana-zk-token-sdk = { git = "https://github.com/anza-xyz/agave.git", version = "=2.1.0" }
spl-associated-token-account = { git = "https://github.com/solana-labs/solana-program-library.git" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.solana]
program-id = "Stake11111111111111111111111111111111111111"
